# Generated by Django 4.2 on 2023-08-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=2, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
