# Generated by Django 4.2 on 2023-09-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_uploadfile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='image',
            field=models.FileField(upload_to='media/%y/%m/%d'),
        ),
    ]
