# Generated by Django 4.2 on 2023-09-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_uploadfile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='image',
            new_name='file',
        ),
    ]
